/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VisitorsIndexImport } from './routes/visitors/index'
import { Route as TheatreIndexImport } from './routes/theatre/index'
import { Route as SupportIndexImport } from './routes/support/index'
import { Route as OnlineIndexImport } from './routes/online/index'
import { Route as LabIndexImport } from './routes/lab/index'
import { Route as KidsIndexImport } from './routes/kids/index'
import { Route as FindIndexImport } from './routes/find/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as AdditionalIndexImport } from './routes/additional/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as VisitorsVisitorImport } from './routes/visitors/$visitor'
import { Route as TheatreTheatreImport } from './routes/theatre/$theatre'
import { Route as SupportSupportImport } from './routes/support/$support'
import { Route as OnlineOnlineImport } from './routes/online/$online'
import { Route as LabLabImport } from './routes/lab/$lab'
import { Route as KidsKidsImport } from './routes/kids/$kids'
import { Route as FindFindImport } from './routes/find/$find'
import { Route as EventsEventImport } from './routes/events/$event'
import { Route as AdditionalAddImport } from './routes/additional/$add'
import { Route as AboutAboutImport } from './routes/about/$about'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VisitorsIndexRoute = VisitorsIndexImport.update({
  path: '/visitors/',
  getParentRoute: () => rootRoute,
} as any)

const TheatreIndexRoute = TheatreIndexImport.update({
  path: '/theatre/',
  getParentRoute: () => rootRoute,
} as any)

const SupportIndexRoute = SupportIndexImport.update({
  path: '/support/',
  getParentRoute: () => rootRoute,
} as any)

const OnlineIndexRoute = OnlineIndexImport.update({
  path: '/online/',
  getParentRoute: () => rootRoute,
} as any)

const LabIndexRoute = LabIndexImport.update({
  path: '/lab/',
  getParentRoute: () => rootRoute,
} as any)

const KidsIndexRoute = KidsIndexImport.update({
  path: '/kids/',
  getParentRoute: () => rootRoute,
} as any)

const FindIndexRoute = FindIndexImport.update({
  path: '/find/',
  getParentRoute: () => rootRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any)

const AdditionalIndexRoute = AdditionalIndexImport.update({
  path: '/additional/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)

const VisitorsVisitorRoute = VisitorsVisitorImport.update({
  path: '/visitors/$visitor',
  getParentRoute: () => rootRoute,
} as any)

const TheatreTheatreRoute = TheatreTheatreImport.update({
  path: '/theatre/$theatre',
  getParentRoute: () => rootRoute,
} as any)

const SupportSupportRoute = SupportSupportImport.update({
  path: '/support/$support',
  getParentRoute: () => rootRoute,
} as any)

const OnlineOnlineRoute = OnlineOnlineImport.update({
  path: '/online/$online',
  getParentRoute: () => rootRoute,
} as any)

const LabLabRoute = LabLabImport.update({
  path: '/lab/$lab',
  getParentRoute: () => rootRoute,
} as any)

const KidsKidsRoute = KidsKidsImport.update({
  path: '/kids/$kids',
  getParentRoute: () => rootRoute,
} as any)

const FindFindRoute = FindFindImport.update({
  path: '/find/$find',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventRoute = EventsEventImport.update({
  path: '/events/$event',
  getParentRoute: () => rootRoute,
} as any)

const AdditionalAddRoute = AdditionalAddImport.update({
  path: '/additional/$add',
  getParentRoute: () => rootRoute,
} as any)

const AboutAboutRoute = AboutAboutImport.update({
  path: '/$about',
  getParentRoute: () => AboutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/about/$about': {
      preLoaderRoute: typeof AboutAboutImport
      parentRoute: typeof AboutImport
    }
    '/additional/$add': {
      preLoaderRoute: typeof AdditionalAddImport
      parentRoute: typeof rootRoute
    }
    '/events/$event': {
      preLoaderRoute: typeof EventsEventImport
      parentRoute: typeof rootRoute
    }
    '/find/$find': {
      preLoaderRoute: typeof FindFindImport
      parentRoute: typeof rootRoute
    }
    '/kids/$kids': {
      preLoaderRoute: typeof KidsKidsImport
      parentRoute: typeof rootRoute
    }
    '/lab/$lab': {
      preLoaderRoute: typeof LabLabImport
      parentRoute: typeof rootRoute
    }
    '/online/$online': {
      preLoaderRoute: typeof OnlineOnlineImport
      parentRoute: typeof rootRoute
    }
    '/support/$support': {
      preLoaderRoute: typeof SupportSupportImport
      parentRoute: typeof rootRoute
    }
    '/theatre/$theatre': {
      preLoaderRoute: typeof TheatreTheatreImport
      parentRoute: typeof rootRoute
    }
    '/visitors/$visitor': {
      preLoaderRoute: typeof VisitorsVisitorImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof AboutImport
    }
    '/additional/': {
      preLoaderRoute: typeof AdditionalIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof rootRoute
    }
    '/find/': {
      preLoaderRoute: typeof FindIndexImport
      parentRoute: typeof rootRoute
    }
    '/kids/': {
      preLoaderRoute: typeof KidsIndexImport
      parentRoute: typeof rootRoute
    }
    '/lab/': {
      preLoaderRoute: typeof LabIndexImport
      parentRoute: typeof rootRoute
    }
    '/online/': {
      preLoaderRoute: typeof OnlineIndexImport
      parentRoute: typeof rootRoute
    }
    '/support/': {
      preLoaderRoute: typeof SupportIndexImport
      parentRoute: typeof rootRoute
    }
    '/theatre/': {
      preLoaderRoute: typeof TheatreIndexImport
      parentRoute: typeof rootRoute
    }
    '/visitors/': {
      preLoaderRoute: typeof VisitorsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute.addChildren([AboutAboutRoute, AboutIndexRoute]),
  AdditionalAddRoute,
  EventsEventRoute,
  FindFindRoute,
  KidsKidsRoute,
  LabLabRoute,
  OnlineOnlineRoute,
  SupportSupportRoute,
  TheatreTheatreRoute,
  VisitorsVisitorRoute,
  AdditionalIndexRoute,
  EventsIndexRoute,
  FindIndexRoute,
  KidsIndexRoute,
  LabIndexRoute,
  OnlineIndexRoute,
  SupportIndexRoute,
  TheatreIndexRoute,
  VisitorsIndexRoute,
])

/* prettier-ignore-end */
